# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (-1, 'Rejected')], default=0)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_accepted', models.DateTimeField(null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'db_table': 'follows',
                'verbose_name_plural': 'Follows',
                'verbose_name': 'Follow',
            },
        ),
    ]
