# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_1',
            new_name='user_from',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_2',
            new_name='user_to',
        ),
    ]
