# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='user_1',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='user_2',
        ),
        migrations.AddField(
            model_name='follow',
            name='date_accepted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='date_requested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (-1, 'Rejected')], default=0),
        ),
    ]
