# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_auto_20170802_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='user_1_to_user_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='user_2_to_user_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Cancelled')], default=0),
        ),
    ]
