# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0003_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='user_1_to_user_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='user_2_to_user_1',
            field=models.BooleanField(default=True),
        ),
    ]
