# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0004_auto_20170822_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_1_to_user_2',
            new_name='user_from_to_user_to',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_2_to_user_1',
            new_name='user_to_to_user_from',
        ),
    ]
