# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='activation_key',
            new_name='email_verification_key',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='activation_key_expires',
            new_name='email_verification_key_expires',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='verification_code',
            new_name='phone_verification_code',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='verification_code_expires',
            new_name='phone_verification_code_expires',
        ),
    ]
