# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilevideo_os_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='profilevideo',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
