# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tink_qrcode',
            field=models.ImageField(null=True, upload_to='tink_qrcodes'),
        ),
    ]
