# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170801_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_permissions': (), 'ordering': ['username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
