# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
