# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20170801_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedphoto',
            options={'default_permissions': (), 'ordering': ['-pk'], 'verbose_name': 'Uploaded Photo', 'verbose_name_plural': 'Uploaded Photos'},
        ),
    ]
