# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20170810_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='photostreamphoto',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
