# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photostreamphoto_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='photostreamphoto',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
