# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_auto_20170823_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='photostream',
            name='send_all_photos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photostreamphoto',
            name='send_photo',
            field=models.BooleanField(default=True),
        ),
    ]
