# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(choices=[(1, 'Email'), (2, 'Push')])),
                ('content', models.TextField()),
                ('subject', models.CharField(max_length=50, null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Successful')], default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'db_table': 'notifications',
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
